In [1]:
import numpy as np 
import pandas as pd


In [19]:
data=['IF YOU’RE NOTHING WITHOUT THIS SUIT, THEN YOU SHOULDN’T HAVE IT.' ,
'IT’S AN IMPERFECT WORLD, BUT IT’S THE ONLY ONE WE’VE GOT.' ,
'JUST BECAUSE SOMETHING WORKS, DOESN’T MEAN IT CAN’T BE IMPROVED.',
      
]

In [20]:
data

['IF YOU’RE NOTHING WITHOUT THIS SUIT, THEN YOU SHOULDN’T HAVE IT.',
 'IT’S AN IMPERFECT WORLD, BUT IT’S THE ONLY ONE WE’VE GOT.',
 'JUST BECAUSE SOMETHING WORKS, DOESN’T MEAN IT CAN’T BE IMPROVED.']

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(ngram_range=(2,2))

If we choose the ngram_range=(1,2), it means that our vocabulary will include both unigrams (individual words) and bigrams (sequences of two words).

In [23]:
bow=cv.fit_transform(data)

In [26]:
bow.toarray()[0]       ## array for IF YOU’RE NOTHING WITHOUT THIS SUIT, THEN YOU SHOULDN’T HAVE IT

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1], dtype=int64)

In [43]:
cv.vocabulary_

{'if you': 7,
 'you re': 29,
 're nothing': 17,
 'nothing without': 14,
 'without this': 26,
 'this suit': 23,
 'suit then': 20,
 'then you': 22,
 'you shouldn': 30,
 'shouldn have': 18,
 'have it': 6,
 'it an': 9,
 'an imperfect': 0,
 'imperfect world': 8,
 'world but': 28,
 'but it': 3,
 'it the': 11,
 'the only': 21,
 'only one': 16,
 'one we': 15,
 'we ve': 25,
 've got': 24,
 'just because': 12,
 'because something': 2,
 'something works': 19,
 'works doesn': 27,
 'doesn mean': 5,
 'mean it': 13,
 'it can': 10,
 'can be': 4,
 'be improved': 1}

In [35]:
new_text=['The only one who can determine this is you']

In [36]:
cv.transform(new_text).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

## if you have OoV(out of Vocabulary) document

In [30]:
oov_data=["my name is khan "]

In [32]:
cv.transform(oov_data).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

it simply ignore the oov words 